name: daily_check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  workspace1_ext:
    name: "ext plan"
    runs-on: ubuntu-latest
    outputs:
      ext_result: ${{ steps.ext-run.outputs.has-changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: kvrhdn/tfe-run@v1
        id: ext-run
        with:
          token: ${{ secrets.TFE_TOKEN }}
          organization: org-test-221226
          workspace: trf_cloud
          type: plan
          wait-for-completion: true
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})

      - name: result check
        run: echo "${{ steps.ext-run.outputs.has-changes }}"

  workspace2_lds:
    name: "lds plan"
    runs-on: ubuntu-latest
    outputs:
      lds_result: ${{ steps.lds-run.outputs.has-changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: kvrhdn/tfe-run@v1
        id: lds-run
        with:
          token: ${{ secrets.TFE_TOKEN }}
          organization: org-test-221226
          workspace: add_ec2
          type: plan
          wait-for-completion: true
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})
      
      - name: result check
        run: echo "${{ steps.lds-run.outputs.has-changes }}"

  workspace3_qa:
    name: "qa plan"
    runs-on: ubuntu-latest
    outputs:
      qa_result: ${{ steps.qa-run.outputs.has-changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: kvrhdn/tfe-run@v1
        id: qa-run
        with:
          token: ${{ secrets.TFE_TOKEN }}
          organization: org-test-221226
          workspace: error
          type: plan
          wait-for-completion: true
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})

      - name: result check
        run: echo "${{ steps.qa-run.outputs.has-changes }}"

  slack_alert:
    name: slack_alert
    runs-on: ubuntu-latest
    needs: [workspace1_ext, workspace2_lds, workspace3_qa]
    steps: 
      - name: get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> GITHUB_ENV

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
{
	"blocks": [
		{
			"type": "header",
			"text": {
				"type": "plain_text",
				"text": "${{ env.DATE }} Terraform Health Check"
			}
		},
		{
			"type": "section",
			"text": {
				"type": "plain_text",
				"text": "변경사항을 감지하여, 없으면 > false / 있으면 > true"
			}
		},
		{
			"type": "divider"
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "ext has changes?"
			},
			"accessory": {
				"type": "button",
				"text": {
					"type": "plain_text",
					"text": "${{ needs.workspace1_ext.outputs.ext_result }}"
				},
				"url": "${{ workspace1_ext.outputs.run-url }}"
			}
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "lds has changes?"
			},
			"accessory": {
				"type": "button",
				"text": {
					"type": "plain_text",
					"text": "${{ needs.workspace2_lds.outputs.lds_result }}"
				},
				"url": "${{ workspace2_lds.outputs.run-url }}"
			}
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "qa has changes?"
			},
			"accessory": {
				"type": "button",
				"text": {
					"type": "plain_text",
					"text": "${{ needs.workspace3_qa.outputs.qa_result }}"
				},
				"url": "${{ workspace3_qa.outputs.run-url }}"
			}
		}
	]
}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK