name: daily_check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  workspace1_ext:
    name: "ext plan"
    runs-on: ubuntu-latest
    outputs:
      ext_result: ${{ steps.ext-run.outputs.has-changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: kvrhdn/tfe-run@v1
        id: ext-run
        type: plan
        wait-for-completion: true
        with:
          token: ${{ secrets.TFE_TOKEN }}
          organization: org-test-221226
          workspace: trf_cloud
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})

      - name: result check
        run: echo "${{ steps.ext-run.outputs.has-changes }}"

  workspace2_lds:
    name: "lds plan"
    runs-on: ubuntu-latest
    outputs:
      lds_result: ${{ steps.lds-run.outputs.has-changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: kvrhdn/tfe-run@v1
        id: lds-run
        type: plan
        wait-for-completion: true
        with:
          token: ${{ secrets.TFE_TOKEN }}
          organization: org-test-221226
          workspace: add_ec2
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})
      
      - name: result check
        run: echo "${{ steps.lds-run.outputs.has-changes }}"

  workspace3_qa:
    name: "qa plan"
    runs-on: ubuntu-latest
    outputs:
      qa_result: ${{ steps.qa-run.outputs.has-changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: kvrhdn/tfe-run@v1
        id: qa-run
        type: plan
        wait-for-completion: true
        with:
          token: ${{ secrets.TFE_TOKEN }}
          organization: org-test-221226
          workspace: error
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})

      - name: result check
        run: echo "${{ steps.qa-run.outputs.has-changes }}"

  slack_alert:
    name: slack_alert
    runs-on: ubuntu-latest
    needs: [workspace1_ext, workspace2_lds, workspace3_qa]
    steps: 
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Terraform Health Check"
                  }
                },      
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*ext:*\n${{ needs.workspace1_ext.outputs.ext_result }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*lds:*\n${{ needs.workspace2_lds.outputs.lds_result }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*qa:*\n${{ needs.workspace3_qa.outputs.qa_result }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK