name: daily_check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  workspace1_ext:
    name: "ext plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: kvrhdn/tfe-run@v1
        with:
          token: ${{ secrets.TFE_TOKEN }}
          organization: org-test-221226
          workspace: trf_cloud
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})
        id: ext-run

  workspace2_lds:
    name: "lds plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: kvrhdn/tfe-run@v1
        with:
          token: ${{ secrets.TFE_TOKEN }}
          organization: org-test-221226
          workspace: add_ec2
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})
        id: lds-run

  workspace3_qa:
    name: "qa plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: kvrhdn/tfe-run@v1
        with:
          token: ${{ secrets.TFE_TOKEN }}
          organization: org-test-221226
          workspace: error
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})
        id: qa-run

  slack_alert:
    name: slack_alert
    runs-on: ubuntu-latest
    needs: [workspace1_ext, workspace2_lds, workspace3_qa]
    steps: 
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # For posting a rich message using Block Kit
          payload:
            {
              "blocks": [
		            {
		            	"type": "header",
		            	"text": {
		            		"type": "plain_text",
		            		"text": "Terraform Health Check",
		            		"emoji": true
		            	}
		            },      
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*ext:*\n${{ steps.workspace1_ext.outputs.has-changes }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*lds:*\n${{ steps.workspace2_lds.outputs.has-changes }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*qa:*\n${{ steps.workspace3_qa.outputs.has-changes }}"
                    },
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK