name: "tfe_run"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tfe_run:
    name: "Terraform"
    runs-on: ubuntu-latest
    id: tfe
    steps:
      - uses: kvrhdn/tfe-run@v1
        with:
          token: ${{ secrets.TFE_TOKEN }}
          organization: org-test-221226
          workspace: trf_cloud
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})
          directory: trf_cloud
          type: plan
          wait-for-completion: true
      - name: echo URL
        run: |
          echo ${{ steps.tfe.outputs.run-url }}
