name: "tfe_run"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tfe_run:
    name: "Terraform"
    runs-on: ubuntu-latest
    
    steps:
      - uses: kvrhdn/tfe-run@v1
        id: tfe
        with:
          token: ${{ secrets.TFE_TOKEN }}
          organization: org-test-221226
          workspace: trf_cloud
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})
          type: plan
          wait-for-completion: true
      - name: echo URL
        if: always()
        run: |
          pwd
          sudo ls -alh .
          echo "----"
          sudo ls -alh /home/runner/work/ 
          echo "----"
          sudo ls -alh /home/runner/work/_temp
          echo "----"
          sudo ls -alh /home/runner/work/_temp/_github_home
          echo "----"
          sudo ls -alh /home/runner/work/_temp/_github_workflow
          echo "----"
          sudo ls -alh /home/runner/work/t101-study
          echo "----"
          sudo ls -alh /var/lib/docker/containers
          echo "----"
          /usr/bin/docker ps -a
          # echo ${{ steps.tfe.outputs.run-url }}
