name: "tfe_run"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tfe_run:
    name: "Terraform"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        id: trf
        with:
          cli_config_credentials_token: ${{ secrets.TFE_TOKEN }}
      - name: Terraform Plan
        id: plan
        run: |
          cd trf_cloud
          terraform init
          terraform plan -no-color
        continue-on-error: true
      - name: echo result
        run: |
          echo ${{ steps.plan.outputs.stdout }}
          echo ${{ steps.plan.outputs.stderr }}
          echo ${{ steps.plan.outputs.exitcode }}
      # - uses: kvrhdn/tfe-run@v1
      #   id: tfe
      #   with:
      #     token: ${{ secrets.TFE_TOKEN }}
      #     organization: org-test-221226
      #     workspace: trf_cloud
      #     message: |
      #       Run triggered using tfe-run (commit: ${{ github.SHA }})
      #     type: plan
      #     wait-for-completion: true
      # - name: echo URL
      #   if: always()
      #   run: |
      #     sudo cat /home/runner/work/_temp/_github_workflow/event.json

